version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Mock env variables based on your credential input
      - PORTFOLIO_USER=topdev
      - PORTFOLIO_PASS=dev@1234
    restart: always
